export const ORDER_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PREPARING: "PREPARING",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
};

export const ACTIVE_ORDER_FLOW = [
  ORDER_STATUS.PENDING_PAYMENT,
  ORDER_STATUS.PREPARING,
  ORDER_STATUS.OUT_FOR_DELIVERY,
  ORDER_STATUS.DELIVERED
];
